### ISSUE TITLE
Naming the RSPM framework package

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/RSPM#2]
The RSPM framework will be made available as a standard R package. As such, it should have a nice and easy-to-say name which has meaning. Given the complex nature of what the framework does, it does not seem very practical to have a simple name and that instead the name will need to be an acronym for a longer name. I have come up with the working name "COSMER" which stands for Collaborative Open Strategic Modeling Environment in R. I think gets at the intent of what we are trying to accomplish. We can easily change what we call this when it moves out of the initial development phase. This issue is to start a discussion on the name we should use.

**Comment by bstabler** [comment]
COSMER sounds good to me.

**Comment by abigazzi** [comment]
I like COSMER - it seems to get all the main points in there. Another option is to add Scalable or Multi-scale or something to communicate the multiple geographies.

**Comment by gregorbj** [comment]
ODOT and FHWA have agreed to use 'VisionEval' as the name for the framework and the model system it supports. This name refers to two key attributes of the model system and supporting software. 'Vision' refers to the use of the system to support strategic planning and visioning. 'Eval' refers to the capabilities of the system and software to evaluate the effects of alternative visions of the future.
