### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/RSPM#3]
We will need to decide on a license for RSPM framework code. An open source license is a must. All of the original GreenSTEP and RSPM code was licensed by ODOT under the GPL license. Newer code has been licensed using the Apache 2 license. I suggest that ODOT license all code using the Apache 2 license.

**Comment by bstabler** [comment]
For open matrix (OMX) we decided on [Apache 2] (http://www.apache.org/licenses/LICENSE-2.0) as well

**Comment by mrspeel** [comment]
ODOT, after consulting with FHWA and ODOT staff, would like to use the Apache 2 license.

**Comment by mrspeel** [comment]
ODOT, after consulting with FHWA and ODOT staff, would like to use the Apache 2 license.

**Comment by gregorbj** [comment]
All code will include Apache 2 license notices.
